### ISSUE TITLE
Create Background Element Components

### ISSUE THREAD

**Issue by RutikKulkarni** [RutikKulkarni/ReferralNetworkHub#18]
#### Task
Develop background elements for ReferralNetworkHub to enhance visual appeal and user experience.

#### Background
Background elements play a crucial role in the aesthetic and usability of web applications. They contribute to the overall design cohesion and user engagement. For ReferralNetworkHub, we aim to implement background components that complement the platform's branding and improve visual appeal across different devices.

#### Scope of Work
1. **Design and Implement Background Components:**
   - Develop reusable background elements using React.js and CSS modules.
   - Ensure responsiveness across desktops, tablets, and mobile devices.
   - Integrate components seamlessly into the existing UI architecture.

2. **Assets Provided:**
   - Figma: https://www.figma.com/file/O25SL6ufvv67r4vBz31jgf/ReferralNetworkHub?type=design&node-id=4%3A19&mode=design&t=h5XaukC9ULBDOzHo-1

#### Expected Deliverables
- Clean and well-structured React components for background elements.
- Responsive design implementation ensuring compatibility across devices.
- Integration into the main project repository following coding standards and best practices.

### Screenshot:
![![image](https://github.com/RutikKulkarni/ReferralNetworkHub/assets/86470947/cdcc1769-4e15-4497-af77-2ab771beb369)](https://github.com/RutikKulkarni/ReferralNetworkHub/assets/86470947/99aa18ab-6690-40ce-957f-1b57ae56a233)

**Comment by KARTIK5799** [comment]
Has anyone been assigned to this task? If not, may I work on it? I've already created the background for this.
<img width="1437" alt="Screenshot 2024-06-16 at 1 15 54 AM" src="https://github.com/RutikKulkarni/ReferralNetworkHub/assets/128450641/5ef357bd-c205-4e69-a945-4f8ac622d8b3">

**Comment by KARTIK5799** [comment]
Has anyone been assigned to this task? If not, may I work on it? I've already created the background for this.
<img width="1437" alt="Screenshot 2024-06-16 at 1 18 18 AM" src="https://github.com/RutikKulkarni/ReferralNetworkHub/assets/128450641/66bd949e-1e26-4a95-903c-12108df96e43">

**Comment by RutikKulkarni** [comment]
> Has anyone been assigned to this task? If not, may I work on it? I've already created the background for this. <img alt="Screenshot 2024-06-16 at 1 18 18 AM" width="1437" src="https://private-user-images.githubusercontent.com/128450641/340024946-66bd949e-1e26-4a95-903c-12108df96e43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MDQ0ODcsIm5iZiI6MTcxODUwNDE4NywicGF0aCI6Ii8xMjg0NTA2NDEvMzQwMDI0OTQ2LTY2YmQ5NDllLTFlMjYtNGE5NS05MDNjLTEyMTA4ZGY5NmU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwMjE2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTFlNDA2NjBkM2ZmYmM4ZTg3MzdjOWQyMDFjZWRlYWJhNTExMTRkZjM4NDE4ZmQzMTJhZDE0MDdmNjM1OTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IJV_7vZQV0vUc7Zy7OSZ1O3jm88pAAwDmf2nlTeBmA8">

Hii, This work has not been assigned to anyone yet, so you can proceed with it. You've created the background for this before, and it turned out great. Please add what you have created to the project as shown in the Figma design. Ensure it works well for mobile, tablet, and desktop (responsive). Now that you are doing this, I will label this issue as assigned.
