### ISSUE TITLE
 Link Home Route to Company Logo Click

### ISSUE THREAD

**Issue by KARTIK5799** [RutikKulkarni/ReferralNetworkHub#28]
https://github.com/RutikKulkarni/ReferralNetworkHub/assets/128450641/6bd1a13e-d4cd-4147-8a55-9363601a9aca

In our project, we currently lack the functionality to navigate to the home page ("/ route") when users click on the company logo. This feature is crucial for improving user experience and ensuring consistent navigation throughout the application. By linking the home route to the company logo, users can easily return to the main page from any part of the application, enhancing usability and intuitiveness.

To address this issue, we need to implement a mechanism that detects clicks on the company logo and redirects users to the home route ("/"). This enhancement will streamline navigation and provide a more cohesive user experience across the application.

**Comment by RutikKulkarni** [comment]
> Screen.Recording.2024-06-16.at.3.08.53.PM.mov 
> In our project, we currently lack the functionality to navigate to the home page ("/ route") when users click on the company logo. This feature is crucial for improving user experience and ensuring consistent navigation throughout the application. By linking the home route to the company logo, users can easily return to the main page from any part of the application, enhancing usability and intuitiveness.
> 
> To address this issue, we need to implement a mechanism that detects clicks on the company logo and redirects users to the home route ("/"). This enhancement will streamline navigation and provide a more cohesive user experience across the application.

Hi, Thank you for highlighting this important aspect of navigation in our project. We understand the significance of linking the company logo to the home page to enhance user experience and ensure consistent navigation.

We are planning to implement this feature in a slightly different way. For logged-in users, the home page will be an "Explore" page, providing a personalized experience. For users who are not logged in, the current home page will remain as it is.

We are currently working on the Figma design for the Explore page, and once that is finalized, we will begin development. This is the reason why the navigation to the home page via the company logo has not been implemented yet.

Thank you for your understanding and patience as we work on these enhancements.

**Comment by KARTIK5799** [comment]
ok no issue
