### ISSUE TITLE
Login and Signup Buttons Not Visible After Deployment

### ISSUE THREAD

**Issue by RutikKulkarni** [RutikKulkarni/ReferralNetworkHub#4]
Upon deployment of the project, it has been observed that the login and signup buttons, which are essential components of the navbar, are not visible. However, during local development, these buttons are displayed correctly. This issue is critical as it affects the usability and functionality of the application for end-users.

Steps to Reproduce:
1. Deploy the project to the target environment.
2. Access the deployed application through the provided URL.
3. Navigate to the navbar section where the login and signup buttons should be visible.

Expected Behavior:
The login and signup buttons should be displayed prominently in the navbar, allowing users to access these essential features of the application.

Actual Behavior:
Upon deployment, the login and signup buttons are not visible in the navbar, causing confusion and hindering user interaction.

Potential Causes:
1. CSS Styling Conflict: There may be CSS rules specific to the deployment environment that are affecting the visibility of the buttons differently from the local environment.
2. Asset Loading Issue: The assets associated with the buttons (such as images or stylesheets) may not be loading correctly in the deployed environment.
3. JavaScript Error: There could be JavaScript errors or conflicts preventing the buttons from rendering as expected.

Resolution Steps:
1. Inspect the deployed application using browser developer tools to identify any CSS rules or styling conflicts affecting the visibility of the buttons.
2. Check the network tab in the browser developer tools to ensure that all assets related to the buttons are loading correctly without any errors.
3. Review any JavaScript code related to the navbar or button functionality to identify and resolve any errors or conflicts.
4. Test potential solutions in a staging environment before deploying them to production to minimize the impact on users.

Additional Information:
- Project URL: https://referral-network-hub.vercel.app/
- Deployment Environment: vercel
- Technologies Used: React, CSS modules
- Screenshots:
  - Local:
![Screenshot 2024-05-12 214748](https://github.com/RutikKulkarni/ReferralNetworkHub/assets/86470947/a9a443f4-4540-465a-9c10-2b66443e159d)

  - Issue on deployed:
![Screenshot 2024-05-12 214903](https://github.com/RutikKulkarni/ReferralNetworkHub/assets/86470947/ce9f4470-adb1-4133-ba88-6b03c8fff942)

**Comment by AbuQamar7379** [comment]
![Screenshot 2024-05-13 133504](https://github.com/RutikKulkarni/ReferralNetworkHub/assets/101246711/ec0ed700-c1c6-47da-9212-9145ea6f8f0a)

RESOLVED, accept pull req!
