### ISSUE TITLE
Improve Name Formatting Logic Based on Number of Cards in Row and Screen Size

### ISSUE THREAD

**Issue by RutikKulkarni** [RutikKulkarni/ReferralNetworkHub#50]
In the `Explore.jsx` component, update the logic for displaying card names to conditionally apply the `formatName` function based on the number of cards in a row and the screen size.

#### Current Behavior:
- All card names are passed through the `formatName` function, regardless of the number of cards in a row or screen size.

#### Desired Behavior:
1. **Based on Number of Cards in Row:**
   - If there is only one card in a row (occupying the full width), the full name should be displayed without any `formatName` logic.
   - If there are 2 or 3 cards in a row, the `formatName` logic should be applied to shorten the names as necessary.

2. **Based on Screen Size:**
   - On mobile devices (screen width ≤ 800px), the `formatName` logic should be applied to all card names, regardless of the number of cards in a row.

#### Impact:
This change will improve the readability and user experience by displaying full names for cards that occupy the entire row while still maintaining a neat and compact display for rows with multiple cards. On mobile devices, all names will be formatted to ensure consistency and optimal use of space.

### Note for Pull Request
When raising the pull request, please attach screenshots of the UI demonstrating that the logic has been successfully implemented. This will help reviewers understand and verify that the desired behavior has been achieved. The screenshots should include:
- A view with only one card in a row, showing the full name displayed.
- A view with 2 or 3 cards in a row, showing the shortened names.
- Views on a mobile device (screen width ≤ 800px), showing all names formatted using the `formatName` function.

**Comment by SomeshPundir** [comment]
Fix: Improved /Adjusted name formatting in Explore cards

I will work to resolve the issue where names were not properly formatted on cards, within provided details
