### ISSUE TITLE
Main Text Row Alignment in `explore.jsx` page

### ISSUE THREAD

**Issue by RutikKulkarni** [RutikKulkarni/ReferralNetworkHub#51]
In the `explore.jsx` page, the `mainText` row containing the `h1` title and search box behaves unexpectedly when users perform a search. Currently, when a user enters a search query in the search box, the `mainText` row, which is intended to remain fixed at the top of the page, shifts to the center of the page if no cards match the search criteria. This behavior occurs across desktop, tablet, and mobile views.

### Expected Behavior
The `mainText` row with the title "Explore" and the search box should remain fixed at the top of the page at all times, irrespective of the search results displayed below it. Even if no cards match the search query, the `mainText` row should not move from its fixed position.

### Steps to Reproduce
1. Navigate to the `explore.jsx` page.
2. Enter a search query in the search box.
3. Observe the position of the `mainText` row.
4. Verify the behavior across different viewport sizes (desktop, tablet, mobile).

### Additional Information
- This issue affects the user experience by causing unexpected movement of UI elements.
- The `explore.jsx` file includes dynamic resizing and filtering logic (`useState`, `useEffect` hooks) to adjust grid layout and card display based on viewport size and search query.

**Comment by Ziphozenkosimthombe** [comment]
So in my understanding I should use the position fixes for the search button, you will correct me if I am wrong.

**Comment by RutikKulkarni** [comment]
> So in my understanding I should use the position fixes for the search button, you will correct me if I am wrong.

You're correct
Using `position: fixed` for the search button will address the issue
Ensure that it functions properly across all screen sizes and devices to maintain a consistent and professional user experience

**Comment by himanshu99256** [comment]
only using position: fixes your footer will not work properly.

**Comment by SomeshPundir** [comment]
[https://drive.google.com/file/d/1_2_HYy6D40hLxEXbePBH9Pb4xu40GhM1/view?usp=sharing](url)
 follow this link to check out if the I successfully did the changes.

**Comment by SomeshPundir** [comment]
I resolved this issue. please check and provide any further scope of improvement.
