### ISSUE TITLE
Mobile View Search Experience in Explore Page

### ISSUE THREAD

**Issue by RutikKulkarni** [RutikKulkarni/ReferralNetworkHub#52]
In the `explore.jsx` page, the current search box behavior on mobile devices does not optimize the user experience effectively. Currently, the search box is always visible and does not expand to full width upon user interaction, nor does it provide contextual feedback when searching for items.

### Expected Behavior
For **mobile devices**:
- Initially, show only a search icon within the `mainText` row next to the title "Explore."
- Upon clicking the search icon, the search box should smoothly expand below the `mainText` row, occupying the full width of the screen.
- After entering a search query:
  - Display a message below the search box showing "Showing results for `{searched text}`" if results are found.
  - Display "No results found for `{searched text}`" if no results match the query.
- Ensure these changes do not affect the fixed positioning of the `mainText` row and maintain responsiveness across different mobile devices.

### Additional Information
- This enhancement aims to improve usability and provide clearer feedback during search interactions on mobile devices.
- The `explore.jsx` file utilizes React hooks (`useState`, `useEffect`) and custom styling (`exploreStyles`) to manage search functionality and UI elements.

**Comment by SomeshPundir** [comment]
The issue has been resolved using the prebuilt component from Uiverse.io and incorporating icons from the ReactIcons library. Additionally, we removed the -> arrow in the mobile version of the explore page to ensure full responsiveness. Any suggestions for further improvement are welcome!
