### ISSUE TITLE
Fix Text Field Alignment Issues on Mobile Screens in EditAccountInfo Page

### ISSUE THREAD

**Issue by RutikKulkarni** [RutikKulkarni/ReferralNetworkHub#59]
There are alignment issues in the "Skills and Expertise" and "Preferences" sections on the `EditAccountInfo` page when viewed on mobile screens. 

## **Problem Details**
1. **"Skills and Expertise" Section:**
   - Text fields appear smaller than expected.
   
2. **"Preferences" Section:**
   - One text field extends outside the screen.
   - Another text field appears smaller than expected.

### **Screenshots:**
![Skills and Expertise" Section](https://github.com/RutikKulkarni/ReferralNetworkHub/assets/86470947/567d2b97-4e4f-4998-b30d-57f83e22d14d)

![Preferences" Section](https://github.com/RutikKulkarni/ReferralNetworkHub/assets/86470947/2e9a42f1-2340-4f6e-93ee-15e5c28f44e3)

### **Acceptance Criteria:**
- Ensure all text fields in the "Skills and Expertise" and "Preferences" sections are correctly aligned on mobile screens.
- Use only the color variables defined in `index.css` to maintain compatibility with both dark and light modes.

### **Additional Information:**
- Make sure the changes do not affect the alignment and appearance of text fields on larger screens.
- **Note:** When raising a pull request, make sure to add screenshots showing the resolved issue.

**Comment by SomeshPundir** [comment]
I checked the Presisting issue, Let me work on it.

**Comment by SomeshPundir** [comment]
https://github.com/RutikKulkarni/ReferralNetworkHub/assets/104303129/ad80c937-1f52-463d-98c5-523ee54b4257
Mobile Irresponsivness in the prefernces component:
The dropdown menu in the Preferences component does not adjust correctly to its container's width when viewed on mobile devices.
