### ISSUE TITLE
Integration of ORMs for easy DB migrations.

### ISSUE THREAD

**Issue by Virajjai** [RutikKulkarni/ReferralNetworkHub#85]
We need to integrate Prisma ORM into project to simplify database migrations and enhance our database management. This will streamline our migration process and improve overall database operations.

**Tasks:**

1. **Install Prisma and its CLI:**
   - Add Prisma to the project dependencies.
   - Configure Prisma with `prisma.schema`.

2. **Configure Database Connection:**
   - Set up Prisma to connect to our existing database.
   - Update environment variables for database credentials.

3. **Define Data Models:**
   - Map out database tables and relationships in the Prisma schema.

4. **Generate Prisma Client:**
   - Use Prisma CLI to generate the client based on the schema.

5. **Implement Migration Strategy:**
   - Execute initial migration to sync Prisma schema with the existing database.

6. **Update Project Codebase:**
   - Refactor code to use Prisma Client for database operations.

7. **Test Integration:**
   - Verify that Prisma Client performs correctly with all database operations.

8. **Documentation:**
   - Update project docs with Prisma setup instructions and usage examples.

**Helpful Documentation Links:**

- [Prisma Getting Started Guide](https://www.prisma.io/docs/getting-started)
- [Prisma Installation Instructions](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch)
- [Prisma Schema Reference](https://www.prisma.io/docs/reference/api-reference/prisma-schema)
- [Prisma Client API](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference)
- [Prisma Migrate Documentation](https://www.prisma.io/docs/concepts/components/prisma-migrate)

**Comment by RutikKulkarni** [comment]
> We need to integrate Prisma ORM into project to simplify database migrations and enhance our database management. This will streamline our migration process and improve overall database operations.
> 
> **Tasks:**
> 
> 1. **Install Prisma and its CLI:**
>    
>    * Add Prisma to the project dependencies.
>    * Configure Prisma with `prisma.schema`.
> 2. **Configure Database Connection:**
>    
>    * Set up Prisma to connect to our existing database.
>    * Update environment variables for database credentials.
> 3. **Define Data Models:**
>    
>    * Map out database tables and relationships in the Prisma schema.
> 4. **Generate Prisma Client:**
>    
>    * Use Prisma CLI to generate the client based on the schema.
> 5. **Implement Migration Strategy:**
>    
>    * Execute initial migration to sync Prisma schema with the existing database.
> 6. **Update Project Codebase:**
>    
>    * Refactor code to use Prisma Client for database operations.
> 7. **Test Integration:**
>    
>    * Verify that Prisma Client performs correctly with all database operations.
> 8. **Documentation:**
>    
>    * Update project docs with Prisma setup instructions and usage examples.
> 
> **Helpful Documentation Links:**
> 
> * [Prisma Getting Started Guide](https://www.prisma.io/docs/getting-started)
> * [Prisma Installation Instructions](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch)
> * [Prisma Schema Reference](https://www.prisma.io/docs/reference/api-reference/prisma-schema)
> * [Prisma Client API](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference)
> * [Prisma Migrate Documentation](https://www.prisma.io/docs/concepts/components/prisma-migrate)

Thanks for the suggestion on Prisma ORM. While Prisma is great, we’re currently using MongoDB, which suits our needs as a schema-less database. Our existing setup already handles database management and migrations efficiently.

If Prisma has specific benefits for MongoDB, we are open to exploring them. But for now, it seems best to stick with our current tools.

Feel free to share any other thoughts!

**Comment by Virajjai** [comment]
Ok as its fits best, we could stick to mongo. Any thing else i could enhance in project.
